#!/bin/bash

Person1=Ramesh
Person2=Suresh

echo "$Person1:: Hello $Person2, How are you?"
echo "$Person2:: Hello $Person1, I am good. How are you?"
echo "$Person1:: I am great, what are you doing now "
echo "$Person2:: I am learning Devops"